Public Enum SpecialFolders
    Desktop
    Home
    Documents
    Pictures
    Downloads
    Videos
    Music
    Favorites
    ThisPc
    Network
    Gallery
    RecycleBin
    Recent
    OneDrivePersonal
    OneDriveBusiness1
    OneDriveBusiness2
    OneDriveBusinessBasic
    OneDriveBusinessStandard
    WindowsTools
    Libraries
    ControlPanel
    DevicesAndPrinters
    AllTasks
    UserProfile
    ProgramsAndFeatures
    User
    InstalledUpdates
    NetworkConnections
    Applications
    [Public]
End Enum
